name: Mirror Main to Codeberg

on:
  push:
    branches:
      - main

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        run: |
          git push --force https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/LGM_Linksanwaelte/rostiger-erhabener-krasser-totaler-allwissender-lichtclient.git main:main
